geomesa-nifi-processors/pom.xml
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/ConvertToGeoAvro.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoMesaKafka.scala
pom.xml

Three big changes:
-> Scala 2.11 packages
-> SFT / Config resolver API changes
-> Kafka vs kafka09 changes

Upgraded GeoMesa to 2.11 v1.3.0

---

CONTRIBUTING.md
build/copyright/ccri.txt
build/copyright/geomesa-header.xml
geomesa-nifi-nar/pom.xml
geomesa-nifi-processors/pom.xml
geomesa-nifi-processors/src/main/java/org/geomesa/nifi/geo/GeomesaConfigControllerService.java
geomesa-nifi-processors/src/main/java/org/geomesa/nifi/geo/GeomesaConfigService.java
geomesa-nifi-processors/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
geomesa-nifi-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/ConvertToGeoAvro.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/IngestMode.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoMesa.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoMesaKafka.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoTools.scala
pom.xml

* Added license headers and license check
* Added contributing.md
* Added style enforcement
* General cleanup
Signed-off-by: Austin Heyne <aheyne@ccri.com>

Cleanup and Licensing

---

README.md

Signed-off-by: Austin Heyne <aheyne@ccri.com>

Added GetHDFS Processor Azure support docs.

---

geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoMesa.scala

Fixes #18 
Tested against Nifi 1.3

flag password fields as sensitive

---

geomesa-nifi-nar/pom.xml
geomesa-nifi-processors-fs/pom.xml
geomesa-nifi-processors-fs/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor
geomesa-nifi-processors-fs/src/main/scala/org/geomesa/nifi/fs/PutGeoMesaFileSystem.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
pom.xml

Signed-off-by: Andrew Hulbert <ahulbert@ccri.com>

#29 PutGeoMesaFileSystem processor

---

geomesa-nifi-processors-fs/src/main/scala/org/geomesa/nifi/fs/PutGeoMesaFileSystem.scala

Updating FSDS parameter imports

---

geomesa-nifi-processors-hbase/src/main/scala/org/geomesa/nifi/hbase/PutGeoMesaHBase.scala

Updating HBase security call

---

geomesa-nifi-processors-fs/src/main/scala/org/geomesa/nifi/fs/PutGeoMesaFileSystem.scala

Updates to FileSystemDataStore parameters

---

geomesa-nifi-processors-kafka/src/main/scala/org/geomesa/nifi/kafka/PutGeoMesaKafka.scala

Fixing disable of kafka consumer

---

geomesa-nifi-processors-kafka/src/main/scala/org/geomesa/nifi/kafka/PutGeoMesaKafka.scala
pom.xml

- Set PutGeoMesaKafka to be a producer only, not a consumer
- Bumped version of Kafka and NiFi

Update NiFi version to 1.4.0, Kafka to 1.0.1

---

geomesa-nifi-processors-accumulo/src/main/scala/org/geomesa/nifi/accumulo/PutGeoMesaAccumulo.scala
geomesa-nifi-processors-fs/src/main/scala/org/geomesa/nifi/fs/PutGeoMesaFileSystem.scala
geomesa-nifi-processors-hbase/src/main/scala/org/geomesa/nifi/hbase/PutGeoMesaHBase.scala
geomesa-nifi-processors-kafka/src/main/scala/org/geomesa/nifi/kafka/PutGeoMesaKafka.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/PutGeoTools.scala

GEOMESA-2269 Allowing HBase to use all data store parameters

---

geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/ConvertToGeoAvro.scala

GEOMESA-2434 Nifi - close converters after use

---

geomesa-nifi-nar/pom.xml
geomesa-nifi-processors-accumulo/src/main/scala/org/geomesa/nifi/accumulo/PutGeoMesaAccumulo.scala
geomesa-nifi-processors-fs/src/main/scala/org/geomesa/nifi/fs/PutGeoMesaFileSystem.scala
geomesa-nifi-processors-hbase/src/main/scala/org/geomesa/nifi/hbase/PutGeoMesaHBase.scala
geomesa-nifi-processors-kafka/src/main/scala/org/geomesa/nifi/kafka/PutGeoMesaKafka.scala
geomesa-nifi-processors-redis/pom.xml
geomesa-nifi-processors-redis/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor
geomesa-nifi-processors-redis/src/main/scala/org/geomesa/nifi/redis/PutGeoMesaRedis.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala
pom.xml

* Simplified loading of data store parameters
* Moved basic validation to AbstractGeoIngestProcessor

Redis NiFi processor

---

geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/AbstractGeoIngestProcessor.scala

Signed-off-by: Andrew Hulbert <ahulbert@ccri.com>

Log processing and conversion at info level

---

.travis.yml
geomesa-nifi-processors-fs/pom.xml
geomesa-nifi-processors-hbase/pom.xml
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/geo/validators/SimpleFeatureTypeValidator.scala
pom.xml

GEOMESA-2712 Fix classpath for loading config files from s3

---

README.md
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/AbstractGeoIngestProcessor.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/datastore/PutGeoMesaAccumulo.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/datastore/PutGeoMesaFileSystem.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/datastore/PutGeoMesaHBase.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/datastore/PutGeoMesaKafka.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/datastore/PutGeoMesaRedis.scala
geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/package.scala

* Remove expression language from converter/sft name to enabled drop-downs

GEOMESA-2723 Add support for expression language based on param metadata 

---

geomesa-nifi-processors-accumulo/src/main/scala/org/geomesa/nifi/accumulo/PutGeoMesaAccumulo.scala

GEOMESA-2732 Fix dispose of shared controller service data store

---

geomesa-nifi-processors/src/main/scala/org/geomesa/nifi/processors/AbstractGeoIngestProcessor.scala

GEOMESA-2740 Property for dynamic converters classpath

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/resources/application.conf
geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AbstractGeoIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConverterIngestProcessor.scala

GEOMESA-2873 Expose flow file attributes in converters

---

geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/SimpleFeatureRecordConverter.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/main/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecord.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/test/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecordTest.scala

GEOMESA-2911 Add visibility col to GetGeoMesaKafkaRecord

---

geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/SimpleFeatureRecordConverter.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/package.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/main/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecord.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/test/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecordTest.scala

GEOMESA-2923 Add user data in GetGeoMesaKafkaRecord processor

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/pom.xml
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/GeoAvroRecordSetWriterFactory.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/RecordIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/SimpleFeatureRecordConverter.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/package.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/test/scala/org/geomesa/nifi/datastore/processor/records/GeoAvroRecordSetWriterFactoryTest.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/main/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecord.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/test/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecordTest.scala
pom.xml

* Implements GeoAvroRecordSetWriter.
* Uses properties or existing SimpleFeature(Type) information.
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

GEOMESA-2906 Create GeoAvroRecordSetWriter

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroIngestProcessor.scala

Signed-off-by: Jim Hughes <jnh5y@ccri.com>

GEOMESA-2925 Fix order bug in GeoMesa NiFi lenient Avro ingest

---

geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AbstractDataStoreProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConverterIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/FeatureTypeProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/package.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/RecordIngestProcessor.scala

GEOMESA-2938 Allow toggle for schema change behavior

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/resources/example-update-2.csv
geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/resources/example-update.csv
geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AbstractDataStoreProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConverterIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/FeatureTypeProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/records/RecordIngestProcessor.scala

GEOMESA-2949 Support modifying writes

---

geomesa-kafka-bundle/geomesa-kafka-processors/src/main/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecord.scala
pom.xml

GEOMESA-2948 Fix GetKafkaRecords offset tracking

---

geomesa-datastore-bundle/geomesa-datastore-processors/pom.xml
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/geotools/GeoToolsProcessor.scala
pom.xml

* Include postgis dependencies by default

GEOMESA-2992 Fix gt-processor to update classpath and validate correctly

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConverterIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/RecordIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/AbstractDataStoreProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/DataStoreIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/DataStoreProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/FeatureWriters.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/service/GeoMesaDataStoreService.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/validators/WriteModeValidator.scala
geomesa-datastore-bundle/geomesa-datastore-services-api/src/main/java/org/geomesa/nifi/datastore/services/DataStoreService.java
geomesa-lambda-bundle/geomesa-lambda-processors/src/main/scala/org/geomesa/nifi/processors/lambda/LambdaDataStoreService.scala

* Move FeatureWriters to separate file
* Simplify FeatureWriters class hierarchy

GEOMESA-3160 Support multi-threading for JDBC data store ingest

---

geomesa-accumulo-bundle/geomesa-accumulo-processors/src/test/scala/org/geomesa/nifi/processors/accumulo/PutGeoMesaAccumuloTest.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/AvroToPutGeoMesa.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConvertToGeoFile.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/ConverterIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/PutGeoMesa.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/PutGeoMesaRecord.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/RecordIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/RecordUpdateProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/UpdateGeoMesaRecord.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/BaseProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/ConvertInputProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/DataStoreIngestProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/FeatureTypeProcessor.scala
geomesa-datastore-bundle/geomesa-datastore-processors/src/main/scala/org/geomesa/nifi/datastore/processor/mixins/package.scala
geomesa-kafka-bundle/geomesa-kafka-processors/src/main/scala/org/geomesa/nifi/processors/kafka/GetGeoMesaKafkaRecord.scala

GEOMESA-3227 Fix processor annotations, for batching in particular

---

build/list-nar.sh
geomesa-datastore-bundle/geomesa-datastore-services-nar/pom.xml
geomesa-hbase-bundle/geomesa-hbase1-nar/pom.xml
pom.xml

* Hadoop 2.10.2 -> 3.3.4
* Woodstox 5.3.0 -> 5.4.0
* HBase 2.5.2 -> 2.5.3-hadoop3, 1.4.13 -> 1.4.14
* commons-net 3.1 -> 3.9.0

GEOMESA-3271 Fix AWS region selection by upgrading Hadoop

---

.github/workflows/main-build.yml
.github/workflows/trivy-scan.yml
build/docker/flow.json
build/docker/logback.xml
build/run-nifi.sh
geomesa-lambda-bundle/geomesa-lambda-processors/src/main/scala/org/geomesa/nifi/processors/lambda/LambdaDataStoreService.scala
pom.xml

* Update ci to not build all branches

GEOMESA-3449 Lambda - persist data in batches
